# Generated by Django 4.0.2 on 2022-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0006_status_order_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='order',
            name='date_finish',
            field=models.DateField(null=True, verbose_name='Дата прибуття'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Дата відправки'),
        ),
    ]
