# Generated by Django 4.0.2 on 2022-04-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0008_alter_order_date_finish_alter_order_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_store.status_order', verbose_name='Статус замовлення'),
        ),
    ]
