# Generated by Django 4.0.5 on 2022-06-09 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_store', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shoppers',
            field=models.ManyToManyField(blank=True, editable=False, related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('link', models.CharField(max_length=36)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
                ('title', models.CharField(max_length=180)),
                ('content', models.CharField(max_length=900)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book_store.book')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('author', 'book')},
            },
        ),
    ]
